openapi: 3.0.3
info:
  title: Vehicle Management API
  version: 1.1.0
servers:
  - url: http://localhost:8080
tags:
  - name: Vehicle Management

paths:
  /vehicles/oneof:
    get:
      operationId: queryVehicles
      tags:
        - Vehicle Management
      summary: Retrieve vehicle information
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 0
        - in: query
          name: size
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VehicleResponse"

components:
  schemas:
    #---------------------------------------------------------------------------
    # Enum utilities
    #---------------------------------------------------------------------------
    VehicleType:
      type: string
      enum: ["CAR", "TRUCK", "CICLE"]
    VehicleColor:
      type: string
      enum: ["RED", "GREEN", "BLUE"]
    #---------------------------------------------------------------------------
    # Model objects
    #---------------------------------------------------------------------------
    VehicleResponse:
      type: object
      required:
        - vehicles
        - paginationInfo
      properties:
        vehicles:
          type: array
          items:
            $ref: "#/components/schemas/Vehicle"
        paginationInfo:
          $ref: "#/components/schemas/PaginationInfo"
    Vehicle:
      type: object
      required:
        - vehicleType
      properties:
        vehicleType:
          type: string
        color:
          type: string
        data:
          $ref: "#/components/schemas/VehicleData"
    PaginationInfo:
      type: object
      required:
        - page
        - size
        - totalElements
        - totalPages
      properties:
        page:
          type: integer
        size:
          type: integer
        numberOfElements:
          type: integer
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
    #---------------------------------------------------------------------------
    # Interface class with discriminator 'vehicleType'
    #---------------------------------------------------------------------------
    VehicleData:
      type: object
      oneOf:
        - $ref: "#/components/schemas/CarData"
        - $ref: "#/components/schemas/TruckData"
        - $ref: "#/components/schemas/CicleData"
      discriminator:
        propertyName: vehicleType
        mapping:
          "CAR": "#/components/schemas/CarData"
          "TRUCK": "#/components/schemas/TruckData"
          "CICLE": "#/components/schemas/CicleData"
    #---------------------------------------------------------------------------
    # Concrete classes
    #---------------------------------------------------------------------------
    VehicleDataBase:
      type: object
      required:
        - vehicleType
      properties:
        vehicleType:
          type: string
    CarData:
      allOf:
        - $ref: "#/components/schemas/VehicleDataBase"
        - type: object
          properties:
            carAttributes:
              type: string
    TruckData:
      allOf:
        - $ref: "#/components/schemas/VehicleDataBase"
        - type: object
          properties:
            truckAttributes:
              type: string
            truckCountWheels:
              type: integer
    CicleData:
      allOf:
        - $ref: "#/components/schemas/VehicleDataBase"
        - type: object
          properties:
            cicleAttributes:
              type: string
            cicleCountWheels:
              type: integer
