openapi: 3.0.3
info:
  title: Usertask Management API
  version: 1.1.0
servers:
  - url: http://localhost:8080

tags:
  - name: Usertask Management

paths:
  /usertasks:
    get:
      operationId: queryUserTasks
      tags:
        - Usertask Management
      summary: Retrieve usertask information
      description: >
        Searches for tasks for a given user. Invoked from the UI.
        Assumption: mTLS for the calling system, userName delegated in parameters. 
        Uses page-based pagination (https://api-patterns.org/patterns/quality/dataTransferParsimony/Pagination)
      parameters:
        - name: type
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/UsertaskType"
        - name: onlyUnclaimed
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/OnlyUnclaimed"
        - name: sortOrder
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/SortOrder"
        - name: pageSize
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/PageSize"
        - name: page
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/PageNumber"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Usertask"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  schemas:
    #---------------------------------------------------------------------------
    # Request params
    #---------------------------------------------------------------------------
    OnlyUnclaimed:
      type: boolean
      example: true
      default: true
    SortOrder:
      type: string
      example: ASCENDING
      default: ASCENDING
      enum:
        - ASCENDING
        - DESCENDING
    PageSize:
      type: integer
      example: 20
      default: 20
      minimum: 1
      maximum: 20
    PageNumber:
      type: integer
      default: 1
      example: 1
      minimum: 1
    #---------------------------------------------------------------------------
    # Common classes
    #---------------------------------------------------------------------------
    AuditMetaData:
      type: object
      required:
        - createdBy
        - createdOn
      properties:
        createdBy:
          type: string
          example: "SCXXXXXX"
          readOnly: true
        createdOn:
          type: string
          format: date-time
          example: "2023-07-31T08:12:34Z"
          readOnly: true
    #---------------------------------------------------------------------------
    # Model objects
    #---------------------------------------------------------------------------
    UserTaskBase:
      allOf:
        - $ref: "#/components/schemas/AuditMetaData"
        - type: object
          required:
            - id
            - status
            - usertaskType
          properties:
            id:
              type: string
            claim:
              $ref: "#/components/schemas/Claim"
            status:
              type: string
              description: "possible values are described in enum UsertaskStatusType"
            usertaskType:
              type: string
              description: "possible values are described in enum UsertaskType"
    Claim:
      type: object
      required:
        - id
        - ownerId
        - ownerFirstname
        - ownerLastname
      properties:
        id:
          type: string
          readOnly: true
        ownerId:
          type: string
          example: "SCXXXXXX"
        ownerFirstname:
          type: string
          example: "Peter"
        ownerLastname:
          type: string
          example: "Muster"
        createdOn:
          type: string
          format: date-time
          example: "2023-07-31T08:12:34Z"
          readOnly: true
    Usertask:
      allOf:
        - $ref: "#/components/schemas/UserTaskBase"
        - type: object
          required:
            - data
          properties:
            data:
              $ref: "#/components/schemas/UserTaskData"
    #---------------------------------------------------------------------------
    # Abstract class with discriminator 'usertaskType'
    #---------------------------------------------------------------------------
    UserTaskData:
      type: object
      description: "possible objects are NameChangeData, AddressChangeData"
      properties:
        usertaskType:
          type: string
          description: "possible values are described in enum UsertaskType"
      discriminator:
        propertyName: usertaskType
        mapping:
          "NAME_CHANGE_TASK": "#/components/schemas/NameChangeData"
          "ADDRESS_CHANGE_TASK": "#/components/schemas/AddressChangeData"
          "NEW_TASK": "#/components/schemas/NewTaskData"
    #---------------------------------------------------------------------------
    # Concrete classes
    #---------------------------------------------------------------------------
    NameChangeData:
      allOf:
        - $ref: "#/components/schemas/UserTaskData"
        - type: object
          required:
            - usertaskType
            - oldName
            - newName
            - evidenceDocumentId
          properties:
            usertaskType:
              type: string
              description: "possible values are described in enum UsertaskType"
            oldName:
              type: string
            newName:
              type: string
            evidenceDocumentId:
              type: string
    AddressChangeData:
      allOf:
        - $ref: "#/components/schemas/UserTaskData"
        - type: object
          required:
            - usertaskType
            - oldAddressLine1
            - newAddressLine1
            - evidenceDocumentId
          properties:
            usertaskType:
              type: string
              description: "possible values are described in enum UsertaskType"
            oldAddressLine1:
              type: string
              example: "addressLine1"
            oldZipCode:
              type: string
              example: "6534"
            oldCity:
              type: string
              example: "some city"
            newAddressLine1:
              type: string
              example: "addressLine1"
            newZipCode:
              type: string
              example: "6534"
            newCity:
              type: string
              example: "some city"
            evidenceDocumentId:
              type: string
    NewTaskData:
      allOf:
        - $ref: "#/components/schemas/UserTaskData"
        - type: object
          required:
            - usertaskType
            - newAttribute
          properties:
            usertaskType:
              type: string
              description: "possible values are described in enum UsertaskType"
            newAttribute:
              type: string
    #---------------------------------------------------------------------------
    # Enum utilities
    #---------------------------------------------------------------------------
    UsertaskStatusType:
      type: string
      example: OPEN
      enum:
        - OPEN
        - COMPLETED
    UsertaskType:
      type: string
      example: NAME_CHANGE_TASK
      enum:
        - NAME_CHANGE_TASK
        - ADDRESS_CHANGE_TASK
        - NEW_TASK
    #---------------------------------------------------------------------------
    # Exception handling
    #---------------------------------------------------------------------------
    UsertaskException:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: string
          nullable: false
          example: <http error code>
        message:
          type: string
          example: "Invalid request parameter"
        details:
          type: array
          items:
            $ref: "#/components/schemas/UsertaskDetailException"
    UsertaskDetailException:
      type: object
      properties:
        field:
          type: string
          example: firstName
        reason:
          type: string
          example: "cannot be blank"
  #---------------------------------------------------------------------------
  # Responses
  #---------------------------------------------------------------------------
  responses:
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UsertaskException"
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UsertaskException"
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UsertaskException"
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UsertaskException"
